Study include
milehighfd/confluence-mhfd-backend pull request #34
Opened 2023-02-22 19:59 UTC by abcussi

2023-02-22 20:14 UTC, LuaXD requested changes

2023-02-22 20:14 UTC, LuaXD commented on src/config/db.js
> +import Study from 'bc/models/study.model';
como todas las variables las estamos llamando en minuscualas estas deberian ser study, codeStudyType, y relatedStudy

2023-02-22 20:14 UTC, LuaXD commented on src/config/db.js
> +import Study from 'bc/models/study.model';
Tambien necesitamos que agregues las relaciones (many to many, one to many , que haya con estos objetos) para que todo funcione normal

2023-02-22 20:14 UTC, LuaXD commented on src/models/code_study_reason.model.js
> +    tableName: 'code_study_reason'
si le quitas estos campos de createdAt, y updatedAt a estos modelso al rato de tratar de hacer create o update va a tratar de agregar ese campo en su sql,son necearios ambos capmos

2023-02-22 20:14 UTC, LuaXD commented on src/models/code_study_sub_reason.model.js
> +    tableName: 'code_study_sub_reason'
misma historia que arriba con createdAt y updateAt

2023-02-22 20:14 UTC, LuaXD commented on src/models/related_study.model.js
> +    tableName: 'related_study'
misma historia que arriba pon ese createdAt y updatedAt en false

2023-02-22 20:14 UTC, LuaXD commented on src/models/stream_study.model.js
> +    freezeTableName: true,
misma historia que arriba pon ese createdAt y updatedAt en false

2023-02-22 20:14 UTC, LuaXD commented on src/models/study.model.js
> +    freezeTableName: true,
misma historia que arriba pon ese createdAt y updatedAt en false

2023-02-22 20:14 UTC, LuaXD commented on src/services/project.service.js
> +          {
le estas mandando isStudy y nunca lo estas usando.

2023-02-22 20:14 UTC, LuaXD commented on src/services/project.service.js
> +            model: ProjectStudy,
en general no llames todos los datos de las tablas o te vas a morir, sobre todo con studies que tiene geometrias que pesan un monton , pedi solo los campos que necesitas

2023-02-22 20:14 UTC, LuaXD commented on src/services/project.service.js
> +const codeStudyType = db.codestudytype;
en este caso todos esos modelos que se llaman aca estan en mayusculas como Objeto (ignoro si esta bien la convención pero la usamos en todo el proyecto, así que mejor lo matienes en mayusculas

2023-02-22 20:14 UTC, LuaXD commented on src/services/project.service.js
> +                  model: Streams
imagino que jala distintos streams respecto a los de arriba??

2023-02-23 18:12 UTC, LuaXD requested changes

2023-02-23 18:12 UTC, LuaXD commented on src/services/project.service.js
> +const getDetails = async (project_id, isStudy) => {
insisto no estas usando isStudy

2023-02-23 18:12 UTC, LuaXD commented on src/services/project.service.js
> +              model: Study,
como te dije no llames todos lso datos, solo los que se van a mostrar y son requeridos por el frontend

2023-02-24 14:21 UTC, Donwilo approved these changes

2023-02-24 14:21 UTC, merged